services:
    schemas_service:
        class:     LearnosityQti\Services\SchemasService
    item_builder_factory:
        class:     LearnosityQti\Processors\QtiV2\In\ItemBuilderFactory
    learnosity_documentation_generator:
        class:     LearnosityQti\DocumentationGenerator
        arguments: ["@schemas_service"]
    learnosity_entity_generator:
        class:     LearnosityQti\EntityGenerator
        arguments: ["@schemas_service"]
    qtiv2_item_mapper:
        class:      LearnosityQti\Processors\QtiV2\In\ItemMapper
        arguments:  ["@item_builder_factory"]
        scope: prototype
    qtiv2_test_mapper:
      class:      LearnosityQti\Processors\QtiV2\In\TestMapper
      scope: prototype
    learnosity_item_writer:
        class:      LearnosityQti\Processors\Learnosity\Out\ItemWriter
        scope:      prototype
    learnosity_activity_writer:
        class:      LearnosityQti\Processors\Learnosity\Out\ActivityWriter
        scope:      prototype
    learnosity_question_writer:
        class:      LearnosityQti\Processors\Learnosity\Out\QuestionWriter
        scope:      prototype
    imscp_manifest_mapper:
        class:      LearnosityQti\Processors\IMSCP\In\ManifestMapper
        scope:      prototype
    learnosity_manifest_writer:
        class:      LearnosityQti\Processors\IMSCP\Out\ManifestWriter
        scope:      prototype

    # QTI Import Processings
    assets_processing:
        class:      LearnosityQti\Processors\QtiV2\In\Processings\AssetsProcessing
    identifiers_processing:
        class:      LearnosityQti\Processors\QtiV2\In\Processings\IdentifiersProcessing
    maths_processing:
        class:      LearnosityQti\Processors\QtiV2\In\Processings\MathsProcessing
    rubrics_processing:
        class:      LearnosityQti\Processors\QtiV2\In\Processings\RubricsProcessing


