services:
    schemas_service:
        class:     Learnosity\Services\SchemasService
    item_builder_factory:
        class:     Learnosity\Mappers\QtiV2\Import\ItemBuilderFactory
    learnosity_documentation_generator:
        class:     Learnosity\QtiImportDocumentationGenerator
        arguments: ["@schemas_service"]
    learnosity_entity_generator:
        class:     Learnosity\EntityGenerator
        arguments: ["@schemas_service"]
    qtiv2_item_mapper:
        class:      Learnosity\Mappers\QtiV2\Import\ItemMapper
        arguments: ["@item_builder_factory"]
        scope: prototype
    qtiv2_test_mapper:
        class:      Learnosity\Mappers\QtiV2\Import\TestMapper
        scope: prototype
    learnosity_item_writer:
        class:      Learnosity\Mappers\Learnosity\Export\ItemWriter
        scope: prototype
    imscp_manifest_mapper:
        class:      Learnosity\Mappers\IMSCP\Import\ManifestMapper
        scope: prototype
    assets_processing:
        class:      Learnosity\Mappers\QtiV2\Import\Processings\AssetsProcessing

