services:
    schemas_service:
        class:     Learnosity\Services\SchemasService
    learnosity_entity_generator:
        class:     Learnosity\EntityGenerator
        arguments: ["@schemas_service"]
    qtiv2_item_mapper:
        class:      Learnosity\Mappers\QtiV2\Import\ItemMapper
    learnosity_item_writer:
        class:      Learnosity\Mappers\Learnosity\Export\ItemWriter
    imscp_manifest_mapper:
        class:      Learnosity\Mappers\IMSCP\Import\ManifestMapper

