services:
    qtism_xml_compat_document:
        class:     qtism\data\storage\xml\XmlCompactDocument
    schemas_service:
        class:     Learnosity\Services\SchemasService
    merged_item_builder:
        class:     Learnosity\Mappers\QtiV2\Import\MergedItemBuilder
    regular_item_builder:
        class:     Learnosity\Mappers\QtiV2\Import\RegularItemBuilder
    learnosity_documentation_generator:
        class:     Learnosity\QtiImportDocumentationGenerator
        arguments: ["@schemas_service"]
    learnosity_entity_generator:
        class:     Learnosity\EntityGenerator
        arguments: ["@schemas_service"]
    qtiv2_item_mapper:
        class:      Learnosity\Mappers\QtiV2\Import\ItemMapper
        arguments: ["@qtism_xml_compat_document", "@merged_item_builder", "@regular_item_builder"]
    qtiv2_test_mapper:
        class:      Learnosity\Mappers\QtiV2\Import\TestMapper
    learnosity_item_writer:
        class:      Learnosity\Mappers\Learnosity\Export\ItemWriter
    imscp_manifest_mapper:
        class:      Learnosity\Mappers\IMSCP\Import\ManifestMapper

